---
- hosts: s1-leaf1, s1-leaf2, s1-leaf3, s1-leaf4, s2-leaf1, s2-leaf2, s2-leaf3, s2-leaf4
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay.yml"
      name: underlay
  - name: Test variables
    debug:
      msg: "{{ underlay[inventory_hostname]['interfaces']['Ethernet3']['ipv4'] }}"
  - name: Create a configuration for Ethernet3
    template:
      src: "{{lookup('env','PWD')}}/templates/leafs-universal.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_universal.cfg"
  - name: Upload config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_universal.cfg"